// data.js — mock people, places, events, conversations. Single source of truth.

// Each person carries an ordered photo deck. Tones repeat with seeds so the
// abstract placeholder painter renders a visibly different composition per slot.
const PHOTO_DECK = (name, tones) => tones.map((tone, i) => ({ id: `${name}-${i}`, tone, seed: `${name}-${i}` }));

const PEOPLE = [
  {
    id: 'maya', name: 'Maya', age: 23, distance: '0.4 mi',
    photos: PHOTO_DECK('Maya', ['peach', 'mint', 'lilac', 'butter', 'rose', 'sky']),
    job: 'comms @ a startup nobody\'s heard of',
    school: 'NYU',
    height: '5\'6"',
    bio: "looking for someone who'll split the bread basket with me. mildly competitive at trivia. crying at A24 movies is my cardio.",
    prompts: [
      { q: 'green flag i look for', a: 'reads physical books in public unironically.' },
      { q: 'two truths and a lie', a: 'lived in lisbon for a year. allergic to mangoes. can name every taylor swift bridge.' },
      { q: 'a non-negotiable', a: 'splits the bill without making it weird.' },
    ],
    tags: ['books', 'matcha', 'gallery hopping', 'cancer'],
    interests: ['books', 'matcha', 'gallery hopping', 'natural wine', 'film cameras', 'thrifting'],
    place: { id: 'attaboy', label: 'Attaboy', tone: 'lilac' },
    verified: true,
    pronouns: 'she/her', here4: 'long-term',
    starSign: 'cancer', drinks: 'socially', smokes: 'never', exercise: 'a few times a week', kids: 'want some',
  },
  {
    id: 'arjun', name: 'Arjun', age: 25, distance: '1.2 mi',
    photos: PHOTO_DECK('Arjun', ['sky', 'butter', 'mint', 'rose', 'peach']),
    job: 'design @ a fintech you\'ve definitely seen ads for',
    school: 'Carnegie Mellon',
    height: '5\'11"',
    bio: "professional yapper. amateur baker. will recommend you a podcast you didn't ask for.",
    prompts: [
      { q: "i'll fall for you if", a: 'you can hang at a noisy bar AND a quiet cafe.' },
      { q: 'sunday morning is for', a: 'pastries, the FT weekend, and judging tourists.' },
      { q: 'my hottest take', a: 'iced coffee in winter is a personality, not a phase.' },
    ],
    tags: ['running', 'design', 'specialty coffee', 'aries'],
    interests: ['running', 'design', 'specialty coffee', 'baking', 'podcasts'],
    place: { id: 'parchm', label: 'Parchm Coffee', tone: 'peach' },
    verified: true,
    pronouns: 'he/him', here4: 'short-term, open to long',
    starSign: 'aries', drinks: 'often', exercise: 'almost daily',
  },
  {
    id: 'simone', name: 'Simone', age: 24, distance: '0.8 mi',
    photos: PHOTO_DECK('Simone', ['rose', 'lilac', 'butter', 'peach', 'mint', 'sky']),
    job: 'gallery assistant + freelance illustrator',
    school: 'RISD',
    height: '5\'4"',
    bio: "i make zines, drink natural wine, and have strong feelings about ceramic mugs.",
    prompts: [
      { q: 'the way to my heart', a: 'a really thoughtful playlist. or a really thoughtless one. surprise me.' },
      { q: 'we\'ll get along if', a: 'you don\'t take yourself too seriously.' },
      { q: 'a perfect first date', a: 'pierogi, then a movie in the park, then crying about it.' },
    ],
    tags: ['art', 'natural wine', 'zines', 'pisces'],
    interests: ['art', 'natural wine', 'zines', 'gallery hopping'],
    place: { id: 'rosesilk', label: 'Rose & Silk', tone: 'rose' },
    verified: true,
    pronouns: 'she/they', here4: 'figuring it out',
    drinks: 'socially',
  },
  {
    id: 'leo', name: 'Leo', age: 26, distance: '2.1 mi',
    photos: PHOTO_DECK('Leo', ['mint', 'sky', 'butter', 'rose']),
    job: 'PT @ a gym i\'ll definitely make you try',
    school: 'UMass',
    height: '6\'1"',
    bio: "yes i lift. yes i cry. multitudes.",
    prompts: [
      { q: 'first round on me if', a: "you've got a niche obsession you can talk about for 10 minutes." },
      { q: 'a recent rabbit hole', a: 'why every coffee shop has the same chair.' },
      { q: 'how i argue', a: 'with a spreadsheet. lovingly.' },
    ],
    tags: ['lifting', 'hiking', 'cooking', 'leo (yes)'],
    interests: ['gym', 'hiking', 'cooking', 'climbing', 'cocktails'],
    place: { id: 'foundry', label: 'The Foundry', tone: 'mint' },
    verified: true,
    pronouns: 'he/him', here4: 'long-term',
    starSign: 'leo', exercise: 'every day', kids: 'open to it', smokes: 'never',
  },
  {
    id: 'iris', name: 'Iris', age: 22, distance: '0.6 mi',
    photos: PHOTO_DECK('Iris', ['peach', 'sky', 'lilac', 'mint', 'butter']),
    job: 'eng student, part-time barista at the one with the good music',
    school: 'Columbia',
    height: '5\'8"',
    bio: 'i contain multitudes. mostly espresso.',
    prompts: [
      { q: 'a weird flex', a: "i've never broken a bone but i've fainted twice on the subway." },
      { q: 'fav genre of disaster', a: 'plans changing 20 min before.' },
      { q: 'best meal i\'ve had', a: 'a bodega egg & cheese after a bad week.' },
    ],
    tags: ['coding', 'film cameras', 'thrifting', 'libra'],
    interests: ['coding', 'film cameras', 'thrifting', 'coffee'],
    place: { id: 'parchm', label: 'Parchm Coffee', tone: 'peach' },
    verified: true,
    pronouns: 'she/her', here4: 'new friends',
  },
  {
    id: 'kai', name: 'Kai', age: 27, distance: '3.4 mi',
    photos: PHOTO_DECK('Kai', ['sky', 'mint', 'butter', 'lilac', 'peach']),
    job: 'product @ a music app',
    school: 'Berklee',
    height: '5\'10"',
    bio: 'i\'ll send you songs at 1am. please pretend to like them.',
    prompts: [
      { q: 'the move on a weeknight', a: 'jazz at a tiny bar that\'s smaller than my apartment.' },
      { q: 'my therapist would say', a: "i'm working on it." },
      { q: 'fav part of nyc', a: 'the one block in dimes square nobody talks about.' },
    ],
    tags: ['music', 'dim sum', 'photography', 'gemini'],
    interests: ['music', 'photography', 'live music', 'dim sum', 'A24', 'letterboxd'],
    place: { id: 'mezzo', label: 'Mezzo Jazz', tone: 'sky' },
    verified: true,
    pronouns: 'he/him', here4: 'short-term, fun',
    starSign: 'gemini', drinks: 'socially', smokes: 'socially / when drinking',
  },
];

const PLACES = [
  { id: 'parchm', label: 'Parchm Coffee', kind: 'Coffee', here: 8, hot: true, vibe: 'quiet study, oat lattes, sage decor', tone: 'peach', dist: '0.2 mi', icon: 'coffee', address: '142 Mott St' },
  { id: 'attaboy', label: 'Attaboy', kind: 'Cocktail bar', here: 23, hot: true, vibe: 'no menu, no rules, low light', tone: 'lilac', dist: '0.4 mi', icon: 'cocktail', address: '134 Eldridge St' },
  { id: 'foundry', label: 'The Foundry', kind: 'Gym + sauna', here: 14, hot: false, vibe: 'sweaty, then social', tone: 'mint', dist: '0.7 mi', icon: 'fire', address: '88 Bleecker St' },
  { id: 'rosesilk', label: 'Rose & Silk', kind: 'Wine bar', here: 19, hot: true, vibe: 'natural wine, soft jazz, the good lighting', tone: 'rose', dist: '0.5 mi', icon: 'cocktail', address: '47 Stanton St' },
  { id: 'mezzo', label: 'Mezzo Jazz', kind: 'Live music', here: 11, hot: false, vibe: 'tuesday sets that turn into thursdays', tone: 'sky', dist: '1.1 mi', icon: 'music', address: '255 W 4th St' },
  { id: 'leaf', label: 'Tompkins Square', kind: 'Park', here: 27, hot: true, vibe: 'sun, dogs, that one good bench', tone: 'mint', dist: '0.9 mi', icon: 'park', address: 'East Village' },
  { id: 'spineco', label: 'Spine & Co.', kind: 'Bookshop', here: 6, hot: false, vibe: 'staff picks you actually trust', tone: 'butter', dist: '0.3 mi', icon: 'book', address: '57 Spring St' },
  { id: 'sliceguy', label: 'Joe\'s Slice', kind: 'Pizza', here: 17, hot: true, vibe: '$3.50 cheese, no questions', tone: 'peach', dist: '0.4 mi', icon: 'pizza', address: '7 Carmine St' },
];

const EVENTS = [
  {
    id: 'nophone',
    title: 'no-phones party',
    host: 'Warehouse 17',
    placeId: null,
    when: 'fri · 10 pm',
    whenShort: 'fri',
    door: '10pm – 4am',
    cover: '$12',
    where: 'warehouse 17, bushwick',
    dist: '1.4 mi',
    going: 184,
    matchesGoing: 6,
    tone: 'lilac',
    icon: 'music',
    vibe: 'phones in a pouch, dance like nobody\'s filming.',
    tags: ['nightlife', 'electronic', '21+', 'sweaty'],
    hot: true,
  },
  {
    id: 'matchawork',
    title: 'matcha & laptops',
    host: 'Parchm Coffee',
    placeId: 'parchm',
    when: 'sun · 11 am',
    whenShort: 'sun',
    door: '11am – 3pm',
    cover: 'free',
    where: 'parchm coffee · nolita',
    dist: '0.2 mi',
    going: 32,
    matchesGoing: 2,
    tone: 'mint',
    icon: 'coffee',
    vibe: 'casual co-working, hot matcha, slow playlist.',
    tags: ['daytime', 'chill', 'wifi', 'solo-friendly'],
    hot: false,
  },
  {
    id: 'openmic',
    title: 'open mic monday',
    host: 'Mezzo Jazz',
    placeId: 'mezzo',
    when: 'mon · 8 pm',
    whenShort: 'mon',
    door: '8pm – 11pm',
    cover: '$5',
    where: 'mezzo jazz · west village',
    dist: '1.1 mi',
    going: 47,
    matchesGoing: 1,
    tone: 'sky',
    icon: 'music',
    vibe: 'mostly poetry, occasionally a saxophone.',
    tags: ['live', 'cozy', 'sit-down', 'BYOB'],
    hot: false,
  },
  {
    id: 'samplesale',
    title: 'sample sale · sat',
    host: 'soft loft co.',
    placeId: null,
    when: 'sat · noon',
    whenShort: 'sat',
    door: '12pm – 6pm',
    cover: 'free',
    where: 'a soho loft (rsvp for addr)',
    dist: '0.8 mi',
    going: 91,
    matchesGoing: 3,
    tone: 'peach',
    icon: 'sparkle',
    vibe: 'thrift, but fancy. cash & cards.',
    tags: ['shopping', 'daytime', 'cute fits', 'rsvp'],
    hot: true,
  },
  {
    id: 'moonyoga',
    title: 'moon yoga',
    host: 'Tompkins Square',
    placeId: 'leaf',
    when: 'wed · 7 pm',
    whenShort: 'wed',
    door: '7pm – 8:30pm',
    cover: 'donate',
    where: 'tompkins square park',
    dist: '0.9 mi',
    going: 64,
    matchesGoing: 4,
    tone: 'butter',
    icon: 'leaf',
    vibe: 'mats provided, please bring chill.',
    tags: ['wellness', 'outdoors', 'sober', 'beginner ok'],
    hot: false,
  },
  {
    id: 'datetrivia',
    title: 'first dates trivia',
    host: 'Attaboy',
    placeId: 'attaboy',
    when: 'thu · 9 pm',
    whenShort: 'thu',
    door: '9pm – 12am',
    cover: '$10',
    where: 'attaboy · LES',
    dist: '0.4 mi',
    going: 58,
    matchesGoing: 5,
    tone: 'rose',
    icon: 'cocktail',
    vibe: 'team up with someone you swiped right on.',
    tags: ['icebreaker', 'cocktails', 'flirty', '21+'],
    hot: true,
  },
];

const MATCHES = [
  { id: 'maya', name: 'Maya', last: 'wait — that\'s the bar i go to', when: '2m', unread: 2, isNew: false,
    anchor: { kind: 'photo', photoIdx: 2, comment: 'okay the bar in your bio — attaboy?' } },
  { id: 'arjun', name: 'Arjun', last: 'okay ranking your top 3 bagels is a personality test', when: '14m', unread: 1, isNew: false,
    anchor: { kind: 'photo', photoIdx: 1, comment: 'the iced-in-winter take is unhinged. say more.' } },
  { id: 'simone', name: 'Simone', last: 'new match', when: 'just now', unread: 0, isNew: true,
    anchor: { kind: 'prompt', q: 'the way to my heart', a: 'a really thoughtful playlist. or a really thoughtless one. surprise me.', comment: 'okay the zine line undid me a little' } },
  { id: 'leo', name: 'Leo', last: 'you free thurs?', when: '1h', unread: 0, isNew: false,
    anchor: { kind: 'photo', photoIdx: 0, comment: null } },
  { id: 'iris', name: 'Iris', last: 'pls i need backup on the subway take', when: 'yesterday', unread: 0, isNew: false,
    anchor: { kind: 'photo', photoIdx: 3, comment: 'the subway-fainting line is sending me' } },
  { id: 'kai', name: 'Kai', last: 'sent you a song. lie if you have to.', when: '2d', unread: 0, isNew: false,
    anchor: { kind: 'photo', photoIdx: 1, comment: null } },
];

const CHATS = {
  maya: [
    { from: 'them', text: 'okay the bar in your bio — attaboy?', t: '8:14 pm' },
    { from: 'me', text: 'guilty. you a regular?', t: '8:14 pm' },
    { from: 'them', text: 'i\'ve been twice this week. don\'t @ me.', t: '8:15 pm' },
    { from: 'me', text: 'a fellow degenerate. love that for us', t: '8:15 pm' },
    { from: 'them', text: 'wait — that\'s the bar i go to', t: '8:16 pm' },
  ],
};

Object.assign(window, { PEOPLE, PLACES, EVENTS, MATCHES, CHATS, PHOTO_DECK });
